### PR TITLE
Enhance strftime of Query Executor

### PR DESCRIPTION
**Pull request by hyoxt121**

### CODE REVIEW

**Comment by shovsj** [comment]
is sqlite built-in strttime also tested?

**Comment by hyoxt121** [comment]
> is sqlite built-in strttime also tested?

Build-in strttime of Sqlite was tested and some of conversions didn't work. So, it was modified using dateutil.parser

**Comment by shovsj** [comment]
the built-in function takes modifiers also. 
strftime(format, timestring, modifier, modifier, ...)
why do you want to override this function?
see https://www.sqlite.org/lang_datefunc.html

**Comment by hyoxt121** [comment]
strftime of sqlite does not work when time = 2016-01-01 0:48. that was the reason. since python doesn't seem to provide overloading, i just excluded when 'modifier' parameters come. now it will work even if strftime has 'modifiers'

**Comment by hyoxt121** [comment]
i do not merge this time. will consider it more.

**Pull request closed without merging**
